### ISSUE TITLE
Root path will fail after Include session help 

### ISSUE THREAD

**Issue by darknessforcetw** [darknessforcetw/sample_app#1]
# Session_helper.erb

module SessionHelper

  def log_in(user)
    session[:user_id] = user.id
  end
## end
# log

Started GET "/" for ::1 at 2015-03-10 09:36:06 +0800

ActionController::RoutingError (uninitialized constant ApplicationController::SessionsHelper):
  app/controllers/application_controller.rb:5:in `<class:ApplicationController>'
  app/controllers/application_controller.rb:1:in`<top (required)>'
  app/controllers/staticpages_controller.rb:1:in `<top (required)>'

  Rendered /Users/blacknight/.rvm/gems/ruby-2.1.3/gems/web-console-2.0.0.beta3/lib/action_dispatch/templates/rescues/_trace.html.erb (1.6ms)
  Rendered /Users/blacknight/.rvm/gems/ruby-2.1.3/gems/web-console-2.0.0.beta3/lib/action_dispatch/templates/rescues/routing_error.html.erb within rescues/layout (21.9ms)

**Comment by darknessforcetw** [comment]
no s
